apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-creds
type: Opaque
data:
  username: {{ .Values.config.db.username | b64enc | quote }}
  password: {{ .Values.config.db.password | b64enc | quote }}
